---
name: Rust Testing
"on":
  push:
  pull_request:
env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: "Run cargo test"
        run: cargo test
      - name: "Build the workspace (debug)"
        run: cargo build --workspace
      - name: "Build the workspace (release)"
        run: cargo build --workspace --release
